name: C-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: make Lab 1
      working-directory: Lab1
      run: make
    - name: make Lab 1 Bonus
      working-directory: Lab1
      run: make
    - name: make Lab 2 Bonus
      working-directory: Lab2/Bonus
      run: make
